Replace AvalDimSharding and MeshDimAssignment with the C++ object.
The sharding and mesh_mapping fields are lists (instead of the current tuple), but they are immutable (it's a readonly property on the C++ object).

2 new `# type: ignore` are needed, because mypy does not understand that List[A] is a List[Union[A, B]]:

```
jax/interpreters/pxla.py:1132: error: Argument "mesh_mapping" to "ShardingSpec" has incompatible type "List[Replicated]"; expected "List[Union[ShardedAxis, Replicated]]"  [arg-type]
jax/interpreters/pxla.py:1132: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
```

PiperOrigin-RevId: 352187814